### ISSUE TITLE
CSS: positioning issues

### ISSUE THREAD

**Issue by bobaaaaa** [stroeer/stroeer-videoplayer#11]
The new videoplayer has a default of `display: inline-flex`. See here:
https://github.com/stroeer/stroeer-videoplayer/blob/aa33923e5bdeec38af956f3f652822a4889337a3/src/StroeerVideoplayer.scss#L8

This works good for all smaller videos. Like in the article body. Unfortunately, this does not look good in our article header / opener. 

Is it possible to change the default here, or do we need to change it by ourselves?

## Info

The screenshots are from localhost. On production there is still the outdated version.

### Actual with `display: inline-flex`

<img width="1058" alt="Bildschirmfoto 2021-09-28 um 18 04 02" src="https://user-images.githubusercontent.com/733158/135124318-a9740d0f-7df2-409d-a055-04478381a791.png">

### Expected with `display: block`

<img width="1033" alt="Bildschirmfoto 2021-09-28 um 18 10 44" src="https://user-images.githubusercontent.com/733158/135125040-b084495f-35e7-4a67-a44d-67b29f864bda.png">

I also need to remove the `position: relative`.

**Comment by walialu** [comment]
@bobaaaaa I see no side-effects on the plugins and the UIs when changing `display: inline-flex` to `display: block`, but when I remove the `position: relative`, then the _big play icon_ gets mis-aligned. Can you confirm this? Or is it just me?

**Comment by bobaaaaa** [comment]
Can confirm: `position: relative` issue is part of our CSS.
